// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn4JUTElPZQ2RMaCY8vKKFaEoTaxNlhfM',
    appId: '1:913873090818:web:95e29d648c7462fe3b2a1b',
    messagingSenderId: '913873090818',
    projectId: 'tallermoviles-624c5',
    authDomain: 'tallermoviles-624c5.firebaseapp.com',
    databaseURL: 'https://tallermoviles-624c5-default-rtdb.firebaseio.com',
    storageBucket: 'tallermoviles-624c5.firebasestorage.app',
    measurementId: 'G-QNFENZDQF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw5ldWDwaIg69FvtlOldI6KG5ei6WQ17s',
    appId: '1:913873090818:android:a5df39cf7a8be8553b2a1b',
    messagingSenderId: '913873090818',
    projectId: 'tallermoviles-624c5',
    databaseURL: 'https://tallermoviles-624c5-default-rtdb.firebaseio.com',
    storageBucket: 'tallermoviles-624c5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWqdN5g5RX_lywD_4IZ-yJ8QTtLKQVqGU',
    appId: '1:913873090818:web:90b41c57412e90673b2a1b',
    messagingSenderId: '913873090818',
    projectId: 'tallermoviles-624c5',
    authDomain: 'tallermoviles-624c5.firebaseapp.com',
    databaseURL: 'https://tallermoviles-624c5-default-rtdb.firebaseio.com',
    storageBucket: 'tallermoviles-624c5.firebasestorage.app',
    measurementId: 'G-G786H0BL82',
  );
}
